# Build React frontend (Airtable + Auth0 env vars are baked in at build time)
FROM node:18-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY public ./public
COPY src ./src

ARG REACT_APP_AUTH0_DOMAIN=placeholder.auth0.com
ARG REACT_APP_AUTH0_CLIENT_ID=placeholder-client-id
ARG REACT_APP_AIRTABLE_API_KEY=placeholder-airtable-key
ARG REACT_APP_AIRTABLE_BASE_ID=appPlaceholderBase
ARG REACT_APP_AIRTABLE_CONTENT_ITEMS_TABLE=ContentItems
ARG REACT_APP_AIRTABLE_CONTENT_BLOCKS_TABLE=ContentBlocks
ARG REACT_APP_AIRTABLE_ITEM_TITLE_FIELD=Title
ARG REACT_APP_AIRTABLE_ITEM_SLUG_FIELD=Slug
ARG REACT_APP_AIRTABLE_ITEM_PUBLISHED_FIELD=Published
ARG REACT_APP_AIRTABLE_BLOCK_ITEM_FIELD=ContentItem
ARG REACT_APP_AIRTABLE_BLOCK_ORDER_FIELD=Order
ARG REACT_APP_AIRTABLE_BLOCK_TYPE_FIELD=Type
ARG REACT_APP_AIRTABLE_BLOCK_PAYLOAD_FIELD=Payload

ENV REACT_APP_AUTH0_DOMAIN=$REACT_APP_AUTH0_DOMAIN
ENV REACT_APP_AUTH0_CLIENT_ID=$REACT_APP_AUTH0_CLIENT_ID
ENV REACT_APP_AIRTABLE_API_KEY=$REACT_APP_AIRTABLE_API_KEY
ENV REACT_APP_AIRTABLE_BASE_ID=$REACT_APP_AIRTABLE_BASE_ID
ENV REACT_APP_AIRTABLE_CONTENT_ITEMS_TABLE=$REACT_APP_AIRTABLE_CONTENT_ITEMS_TABLE
ENV REACT_APP_AIRTABLE_CONTENT_BLOCKS_TABLE=$REACT_APP_AIRTABLE_CONTENT_BLOCKS_TABLE
ENV REACT_APP_AIRTABLE_ITEM_TITLE_FIELD=$REACT_APP_AIRTABLE_ITEM_TITLE_FIELD
ENV REACT_APP_AIRTABLE_ITEM_SLUG_FIELD=$REACT_APP_AIRTABLE_ITEM_SLUG_FIELD
ENV REACT_APP_AIRTABLE_ITEM_PUBLISHED_FIELD=$REACT_APP_AIRTABLE_ITEM_PUBLISHED_FIELD
ENV REACT_APP_AIRTABLE_BLOCK_ITEM_FIELD=$REACT_APP_AIRTABLE_BLOCK_ITEM_FIELD
ENV REACT_APP_AIRTABLE_BLOCK_ORDER_FIELD=$REACT_APP_AIRTABLE_BLOCK_ORDER_FIELD
ENV REACT_APP_AIRTABLE_BLOCK_TYPE_FIELD=$REACT_APP_AIRTABLE_BLOCK_TYPE_FIELD
ENV REACT_APP_AIRTABLE_BLOCK_PAYLOAD_FIELD=$REACT_APP_AIRTABLE_BLOCK_PAYLOAD_FIELD

RUN npm run build

# Production runtime: nginx serving the static SPA
FROM nginx:1.27-alpine AS production

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \
  CMD wget -qO- http://127.0.0.1/ > /dev/null || exit 1

CMD ["nginx", "-g", "daemon off;"]
